### ISSUE TITLE
Multiple requests at the same time issue

### ISSUE THREAD

**Issue by Moriarty178** [PTIT-DATN-2024/Back-end#20]
Ex, Product x với quantity = 7, lúc này nhận được 4 request order x, mỗi request order 4x hoặc nhiều biến thế khác như 10 req mỗi request 2, 3 request mỗi request 7x... 
Đại thể là không tuần tự theo thời gian order nên không check quantity sau mỗi order được, dẫn tới issues:
⚠️ : total_quantity_request > quantity_product

**Comment by HaiDang-183** [comment]
Dùng Vector Clock.
